### ISSUE TITLE
Sass warning: unclear import

### ISSUE THREAD

**Issue by dmke** [kristianmandrup/world-flags#16]
```
WARNING: On line 3 of /…/app/assets/stylesheets/components/_flags.css.sass:
  It's not clear which file to import for '@import "flags/flags24"'.
  Candidates:
    flags/flags24.css.erb
    flags/flags24.css.scss.erb
  For now I'll choose flags24.css.erb.
  This will be an error in future versions of Sass.
```

I think it is safe to assume that Rails 3.1+ applications will make use of the asset pipeline. If you agree, I'd suggest to
- remove the `.css.erb` files
- add [`sass`](/nex3/sass) as runtime dependency to your gemspec

To go a step further, I'd remove the ERb processing completely and rely solely on the `image-url` helper from [`sass-rails`](/rails/sass-rails), e.g.:

``` scss
.flag16 {
  background: image-url("flags/flags16.png") no-repeat;
}
```

**Comment by Arugin** [comment]
If you don't maintain this just pass this repo to people who wants to maintain.

**Comment by kristianmandrup** [comment]
Yeah, I hardly ever use Ruby or Rails anymore. If anyone is interested in taking over, please let me know.

**Comment by Arugin** [comment]
I can continue to support this gem.

**Comment by kristianmandrup** [comment]
@Arugin Super, I will give you admin access
