### ISSUE TITLE
Maintainership of world-flags

### ISSUE THREAD

**Issue by jspanjers** [kristianmandrup/world-flags#19]
Hi,

As Kristian indicated that he no longer maintains this gem [1], I'd like to volunteer to start maintaining it. I have set up a new organization on github, forking the world-flags repository [2].

To this new repository, I have committed a few patches fixing open issues in the world-flags current release. I have also added a new release 0.7.0, which I would like to publish on rubygems.
This release will add support for Rails 4+.

I have set up the new repository under a new organization 'world-flags' instead of using a personal github repository in the hope of attracting co-maintainers.

[1] https://github.com/kristianmandrup/world-flags/issues/16
[2] https://github.com/world-flags/world-flags

**Comment by kristianmandrup** [comment]
Super!!! Go for it :)

**Comment by kristianmandrup** [comment]
You are now the proud owner of world-flags :)
